logging:
  file:
    path: ${user.dir}/logs
  level:
    apm: DEBUG
    jdbc:
      audit: false
      connection: false
      resultset: false
      resultsettable: false
      sqlonly: false
      sqltiming: ERROR
    org:
      hibernate: false
      springframework:
        boot: INFO
    root: warn
  pattern:
    console: '"%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"'
    file: '"%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"'

